:username_comments_index:
    path:     /comments
    defaults: { _controller: "GithubBundle:Comments:index" }
    methods:  GET


:username_comments_new:
    path:     /{username}/comments
    defaults: { _controller: "GithubBundle:Comments:new" }
    methods:  [GET, POST]

:username_comments_edit:
    path:     /{id}/{username}/edit
    defaults: { _controller: "GithubBundle:Comments:edit" }
    methods:  [GET, POST]

:username_comments_delete:
    path:     /{id}/{username}/delete
    defaults: { _controller: "GithubBundle:Comments:delete" }
    methods:  [GET, DELETE]
